version: "3.8"

services:
    # Frontend контейнер
    frontend:
        image: ${REGISTRY:-}aregrp-frontend:${TAG:-local}
        build: frontend
        container_name: aregrp-frontend
        restart: unless-stopped
        networks:
            - frontend-network
        volumes:
            # Для hot reload в development режиме (опционально)
            - ./frontend/src:/app/src:ro
        environment:
            - NODE_ENV=production

    # Backend контейнер
    #   backend:
    #     build:
    #       context: ./backend
    #       dockerfile: Dockerfile
    #     container_name: aregrp-backend
    #     restart: unless-stopped
    #     ports:
    #       - "3000:3000"
    #     networks:
    #       - backend-network
    #     volumes:
    #       # Для hot reload в development режиме (опционально)
    #       - ./backend:/app:ro
    #       - /app/node_modules
    #     environment:
    #       - NODE_ENV=production
    #       - PORT=3000

    # Nginx reverse proxy
    nginx:
        image: ${REGISTRY:-}aregrp-nginx:${TAG:-local}
        build: nginx
        container_name: aregrp-nginx
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/logs:/var/log/nginx
        depends_on:
            - frontend
            # - backend
        networks:
            - frontend-network
            - backend-network

networks:
    frontend-network:
        driver: bridge
    backend-network:
        driver: bridge

volumes:
    nginx-cache:
        driver: local
