services:
    # Frontend контейнер
    frontend:
        image: ${REGISTRY_PREFIX:-}aregrp-frontend:${TAG:-local}
        build: frontend
        container_name: aregrp-frontend
        restart: unless-stopped
        networks:
            - frontend-network
        volumes:
            # Для hot reload в development режиме (опционально)
            - ./frontend/src:/app/src:ro
        environment:
            - NODE_ENV=production

    db:
        image: postgres:17
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        env_file:
            - ./backend/.env.postgres
        networks:
            - django-network
        restart: always

    backend:
        image: ${REGISTRY_PREFIX:-}aregrp-backend:${TAG:-local}
        build: backend
        container_name: aregrp-backend
        ports:
            - "8000:8000"
        depends_on:
            - db
        volumes:
            - ./media:/app/media
            - ./static:/app/static
        env_file:
            - ./backend/.env
            - ./backend/.env.postgres
        networks:
            - backend-network
            - django-network
        restart: always

    # Nginx reverse proxy
    nginx:
        image: ${REGISTRY_PREFIX:-}aregrp-nginx:${TAG:-local}
        build: nginx
        container_name: aregrp-nginx
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            # Переписываем только изменения (ост авляем все дефолтное)
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/conf.d:/etc/nginx/conf.d:ro
            - ./nginx/includes:/etc/nginx/includes:ro
            - ./nginx/error-templates:/etc/nginx/error-templates:ro
            - ./nginx/logs:/var/log/nginx
            - nginx-cache:/var/cache/nginx
        depends_on:
            - frontend
            - backend
        networks:
            - frontend-network
            - backend-network

networks:
    frontend-network:
        driver: bridge
    backend-network:
        driver: bridge
    django-network:
        driver: bridge

volumes:
    nginx-cache:
        driver: local
