line-length = 120
target-version = "py312"

[format]
quote-style = "single"
indent-style = "space"
line-ending = "auto"

[lint]
select = ["E", "F", "B", "I", "N", "SIM", "UP"]

[lint.isort]
combine-as-imports = true
force-single-line = false